name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Job
        run: echo "Hello, ${{ github.actor }}!"

  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Job 1
        run: echo "This job tests something"

  test2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Job 2
        run: |
          echo "This job tests something, but takes more time than test-job1."
          echo "After the echo commands complete, it runs the sleep command for 20 seconds"
          echo "which simulates a test that runs 20 seconds longer than test-job1"
          sleep 20

  deploy:
    needs: [build, test1, test2]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Production
        run: echo "This job deploys something from the ${{ github.ref }} branch."
